sudo: required

language: generic

services:
  - docker

brfore_install:
  - echo "start Createing an image with dockerfile"
  - docker build -t jinyoung36/react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true jinyoung36/react-app npm run test -- --coverage

after_success:
  - echo "Test Success"